//===---- SDICISelDAGToDAG.h - A Dag to Dag Inst Selector for SDIC --------===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file defines an instruction selector for the SDIC target.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_SDIC_SDICISELDAGTODAG_H
#define LLVM_LIB_TARGET_SDIC_SDICISELDAGTODAG_H

#include "SDICConfig.h"

#include "SDIC.h"
#include "SDICSubtarget.h"
#include "SDICTargetMachine.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"

//===----------------------------------------------------------------------===//
// Instruction Selector Implementation
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// SDICDAGToDAGISel - SDIC specific code to select SDIC machine
// instructions for SelectionDAG operations.
//===----------------------------------------------------------------------===//
namespace llvm {

class SDICDAGToDAGISel : public SelectionDAGISel {
public:
  explicit SDICDAGToDAGISel(SDICTargetMachine &TM, CodeGenOpt::Level OL)
      : SelectionDAGISel(TM, OL), Subtarget(nullptr) {}

  // Pass Name
  const char *getPassName() const override {
    return "SDIC DAG->DAG Pattern Instruction Selection";
  }

  bool runOnMachineFunction(MachineFunction &MF) override;

protected:
  SDNode *getGlobalBaseReg();
  
  /// Keep a pointer to the SDICSubtarget around so that we can make the right
  /// decision when generating code for different targets.
  const SDICSubtarget *Subtarget;

private:
  // Include the pieces autogenerated from the target description.
  #include "SDICGenDAGISel.inc"

  /// getTargetMachine - Return a reference to the TargetMachine, casted
  /// to the target-specific type.
  const SDICTargetMachine &getTargetMachine() {
    return static_cast<const SDICTargetMachine &>(TM);
  }

  void Select(SDNode *N) override;

  virtual bool trySelect(SDNode *Node) = 0;

  // Complex Pattern.
  bool SelectAddr(SDNode *Parent, SDValue N, SDValue &Base, SDValue &Offset);

  // getImm - Return a target constant with the specified value.
  inline SDValue getImm(const SDNode *Node, unsigned Imm) {
    return CurDAG->getTargetConstant(Imm, SDLoc(Node), Node->getValueType(0));
  }

  virtual void processFunctionAfterISel(MachineFunction &MF) = 0;

};

}

#endif

